# Task 1:
# Use istioctl analyse -n gateway-debug-lab can show issues sometimes

apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: portal-gateway
  namespace: gateway-debug-lab
spec:
  selector:
    istio: ingressgateway # This was wrong (put correct label for your Istio ingress gateway)
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - portal.debug.example

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: portal
  namespace: gateway-debug-lab
spec:
  hosts:
    - portal.debug.example
  gateways:
    - portal-gateway
  http:
    - route:
        - destination:
            host: portal.gateway-debug-lab.svc.cluster.local # ns was wrong in this
            port:
              number: 8080 # This was wrong
