apiVersion: v1
kind: Namespace
metadata:
  name: weighting-lab
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: weighting-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
        - name: reviews
          image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  namespace: weighting-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
        - name: reviews
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: weighting-lab
spec:
  selector:
    app: reviews
  ports:
    - name: http
      port: 80
      targetPort: 8080
