apiVersion: v1
kind: Namespace
metadata:
  name: vs-dr-lab
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: vs-dr-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
        - name: reviews
          image: hashicorp/http-echo:1.0.0
          args: ["-listen=:8080", "-text=reviews-v1"]
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  namespace: vs-dr-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
        - name: reviews
          image: hashicorp/http-echo:1.0.0
          args: ["-listen=:8080", "-text=reviews-v2"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: vs-dr-lab
spec:
  selector:
    app: reviews
  ports:
    - name: http
      port: 80
      targetPort: 8080
