apiVersion: v1
kind: Namespace
metadata:
  name: workload-entry-lab
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-sa
  namespace: workload-entry-lab
