# Task 1: Delay fault
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ratings
  namespace: ratings
spec:
  hosts:
    - ratings
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 100
    route:
      - destination:
          host: ratings
---
# Task 2: Error fault
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ratings
  namespace: api
spec:
  hosts:
    - api-server
  http:
  - match:
    - headers:
        end-user:
          exact: test-account
    fault:
    abort:
      httpStatus: 501
      percentage:
        value: 100
    route:
      - destination:
          host: api-server
  - route:
    - destination:
        host: api-server
