apiVersion: v1
kind: Namespace
metadata:
  name: canary-upgrade-lab
  labels:
    istio.io/rev: 1-21-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: canary-upgrade-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hashicorp/http-echo:1.0.0
          args:
            - -listen=:8080
            - -text=canary-upgrade
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: canary-upgrade-lab
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
