apiVersion: v1
kind: Namespace
metadata:
  name: injection-auto
---
apiVersion: v1
kind: Namespace
metadata:
  name: no-injection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: injection-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: no-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx
