# Task 1: Basic Sidecar (namespace level)
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: default-egress
  namespace: sidecar-lab
spec:
  egress:
    - hosts:
        - "./*"
        - "istio-system/*"
        - "security/*"
---
# Task 2: Selector-specific Sidecar
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: super-egress
  namespace: super-security
spec:
  workloadSelector:
    labels:
      app: payments
  egress:
    - hosts:
        - "./*"
        - "istio-system/*"
