# Task 1: DNS ServiceEntry
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: cool-se
  namespace: cool
spec:
  hosts:
    - cool-url.lab
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
---
# Task 2: IP ServiceEntry
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: warm-se
  namespace: warm
spec:
  hosts:
    - warm-url.lab
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: 193.184.216.34
---
# Task 3: Virtual Service
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: warm-vs
  namespace: warm
spec:
  hosts:
    - warm-url.lab
  http:
    - route:
        - destination:
            host: warm-url.lab
            port:
              number: 80
