apiVersion: v1
kind: Namespace
metadata:
  name: service-entry-lab
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: service-entry-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: curlimages/curl:8.7.1
          command: ["/bin/sh", "-c", "sleep 365d"]
