# Task 1: Circuit breaker policy
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin
  namespace: circuit-breaker-lab
spec:
  host: httpbin
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        maxRequestsPerConnection: 5
    outlierDetection:
      consecutive5xxErrors: 2
